name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_DEFAULT_TRIPLET: wasm32-emscripten
    steps:
      - uses: mymindstorm/setup-emsdk@v14

      - name: Verify
        run: emcc -v

      - run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh